# Generated by Django 4.1.7 on 2023-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='win_flag',
            field=models.BooleanField(null=True),
        ),
    ]
