from django.core.management.base import BaseCommand
from smash_note.models import Character

class Command(BaseCommand):
    help = 'Creates all character data in the database'

    def handle(self, *args, **options):
        characters = [
            {"character_id":1,"character_name":"マリオ","img_path":"mario.jpg"},
            {"character_id":2,"character_name":"ドンキーコング","img_path":"donkey.jpg"},
            {"character_id":3,"character_name":"リンク","img_path":"link.jpg"},
            {"character_id":4,"character_name":"サムス","img_path":"samus.jpg"},
            {"character_id":5,"character_name":"ダークサムス","img_path":"dark_samus.jpg"},
            {"character_id":6,"character_name":"ヨッシー","img_path":"yoshi.jpg"},
            {"character_id":7,"character_name":"カービー","img_path":"kirby.jpg"},
            {"character_id":8,"character_name":"フォックス","img_path":"fox.jpg"},
            {"character_id":9,"character_name":"ピカチュウ","img_path":"pikachu.jpg"},
            {"character_id":10,"character_name":"ルイージ","img_path":"luigi.jpg"},
            {"character_id":11,"character_name":"ネス","img_path":"ness.jpg"},
            {"character_id":12,"character_name":"CF","img_path":"captain_falcon.jpg"},
            {"character_id":13,"character_name":"プリン","img_path":"purin.jpg"},
            {"character_id":14,"character_name":"ピーチ","img_path":"peach.jpg"},
            {"character_id":15,"character_name":"デイジー","img_path":"daisy.jpg"},
            {"character_id":16,"character_name":"クッパ","img_path":"koopa.jpg"},
            {"character_id":17,"character_name":"アイスクライマー","img_path":"ice_climber.jpg"},
            {"character_id":18,"character_name":"シーク","img_path":"sheik.jpg"},
            {"character_id":19,"character_name":"ゼルダ","img_path":"zelda.jpg"},
            {"character_id":20,"character_name":"ドクターマリオ","img_path":"drmario.jpg"},
            {"character_id":21,"character_name":"ピチュー","img_path":"pichu.jpg"},
            {"character_id":22,"character_name":"ファルコ","img_path":"falco.jpg"},
            {"character_id":23,"character_name":"マルス","img_path":"marth.jpg"},
            {"character_id":24,"character_name":"ルキナ","img_path":"lucina.jpg"},
            {"character_id":25,"character_name":"こどもリンク","img_path":"young_link.jpg"},
            {"character_id":26,"character_name":"ガノンドロフ","img_path":"ganondorf.jpg"},
            {"character_id":27,"character_name":"ミューツー","img_path":"mewtwo.jpg"},
            {"character_id":28,"character_name":"ロイ","img_path":"roy.jpg"},
            {"character_id":29,"character_name":"クロム","img_path":"chrom.jpg"},
            {"character_id":30,"character_name":"ゲーム＆ウォッチ","img_path":"game_and_watch.jpg"},
            {"character_id":31,"character_name":"メタナイト","img_path":"meta_knight.jpg"},
            {"character_id":32,"character_name":"ピット","img_path":"pit.jpg"},
            {"character_id":33,"character_name":"ブラックピット","img_path":"black_pit.jpg"},
            {"character_id":34,"character_name":"ゼロスーツサムス","img_path":"zero_suit_samus.jpg"},
            {"character_id":35,"character_name":"ワリオ","img_path":"wario.jpg"},
            {"character_id":36,"character_name":"スネーク","img_path":"snake.jpg"},
            {"character_id":37,"character_name":"アイク","img_path":"ike.jpg"},
            {"character_id":38,"character_name":"ポケトレ","img_path":"Pokemon_trainer.jpg"},
            {"character_id":39,"character_name":"ディディコング","img_path":"dd.jpg"},
            {"character_id":40,"character_name":"ルカ","img_path":"lucas.jpg"},
            {"character_id":41,"character_name":"ソニック","img_path":"sonic.jpg"},
            {"character_id":42,"character_name":"デデデ","img_path":"ddd.jpg"},
            {"character_id":43,"character_name":"ピクオリ","img_path":"pikumin_and_orimar.jpg"},
            {"character_id":44,"character_name":"ルカリオ","img_path":"lucario.jpg"},
            {"character_id":45,"character_name":"ロボット","img_path":"robot.jpg"},
            {"character_id":46,"character_name":"トゥーンリンク","img_path":"toon_link.jpg"},
            {"character_id":47,"character_name":"ウルフ","img_path":"wolf.jpg"},
            {"character_id":48,"character_name":"村人","img_path":"murabito.jpg"},
            {"character_id":49,"character_name":"ロックマン","img_path":"rockman.jpg"},
            {"character_id":50,"character_name":"フィットレ","img_path":"fit_trainer.jpg"},
            {"character_id":51,"character_name":"ロゼチコ","img_path":"rose_chiko.jpg"},
            {"character_id":52,"character_name":"リトルマック","img_path":"little_mac.jpg"},
            {"character_id":53,"character_name":"ゲッコウガ","img_path":"gekkouga.jpg"},
            {"character_id":54,"character_name":"パルテナ","img_path":"palutena.jpg"},
            {"character_id":55,"character_name":"パックマン","img_path":"pac_man.jpg"},
            {"character_id":56,"character_name":"ルフレ","img_path":"reflet.jpg"},
            {"character_id":57,"character_name":"シュルク","img_path":"shulk.jpg"},
            {"character_id":58,"character_name":"クッパジュニア","img_path":"koopa_jr.jpg"},
            {"character_id":59,"character_name":"ダックハント","img_path":"duck_hunt.jpg"},
            {"character_id":60,"character_name":"リュウ","img_path":"ryu.jpg"},
            {"character_id":61,"character_name":"ケン","img_path":"ken.jpg"},
            {"character_id":62,"character_name":"クラウド","img_path":"cloud.jpg"},
            {"character_id":63,"character_name":"カムイ","img_path":"kamui.jpg"},
            {"character_id":64,"character_name":"ベヨネッタ","img_path":"bayonetta.jpg"},
            {"character_id":65,"character_name":"インクリング","img_path":"inkling.jpg"},
            {"character_id":66,"character_name":"リドリー","img_path":"ridley.jpg"},
            {"character_id":67,"character_name":"シモン","img_path":"simon.jpg"},
            {"character_id":68,"character_name":"リヒター","img_path":"richter.jpg"},
            {"character_id":69,"character_name":"キングクルール","img_path":"king_k_rool.jpg"},
            {"character_id":70,"character_name":"しずえ","img_path":"shizue.jpg"},
            {"character_id":71,"character_name":"ガオガエン","img_path":"gaogaen.jpg"},
            {"character_id":72,"character_name":"パックンフラワー","img_path":"packun_flower.jpg"},
            {"character_id":73,"character_name":"ジョーカー","img_path":"joker.jpg"},
            {"character_id":74,"character_name":"勇者","img_path":"hero.jpg"},
            {"character_id":75,"character_name":"バンカズ","img_path":"bankazu.jpg"},
            {"character_id":76,"character_name":"テリー","img_path":"terry.jpg"},
            {"character_id":77,"character_name":"ベレス","img_path":"byleth.jpg"},
            {"character_id":78,"character_name":"メンメン","img_path":"minmin.jpg"},
            {"character_id":79,"character_name":"スティーブ","img_path":"steve.jpg"},
            {"character_id":80,"character_name":"セフィロス","img_path":"sephiroth.jpg"},
            {"character_id":81,"character_name":"ホムヒカ","img_path":"homuhika.jpg"},
            {"character_id":82,"character_name":"カズヤ","img_path":"kazuya.jpg"},
            {"character_id":83,"character_name":"ソラ","img_path":"sora.jpg"},
            {"character_id":84,"character_name":"格闘mii","img_path":"mii_brawler.jpg"},
            {"character_id":85,"character_name":"剣術mii","img_path":"mii_sword.jpg"},
            {"character_id":86,"character_name":"射撃mii","img_path":"mii_gunner.jpg"},
        ]

        for data in characters:
            character = Character(**data)
            character.save()
            
        self.stdout.write(self.style.SUCCESS('this command Success'))