from django.core.management.base import BaseCommand
from smash_note.models import Character

class Command(BaseCommand):
    help = 'Creates all character data in the database'

    def handle(self, *args, **options):
        characters = [
            {"character_name":"マリオ","image_url":"mario.jpg"},
            {"character_name":"ドンキーコング","image_url":"donkey.jpg"},
            {"character_name":"リンク","image_url":"link.jpg"},
            {"character_name":"サムス","image_url":"samus.jpg"},
            {"character_name":"ダークサムス","image_url":"dark_samus.jpg"},
            {"character_name":"ヨッシー","image_url":"yoshi.jpg"},
            {"character_name":"カービー","image_url":"kirby.jpg"},
            {"character_name":"フォックス","image_url":"fox.jpg"},
            {"character_name":"ピカチュウ","image_url":"pikachu.jpg"},
            {"character_name":"ルイージ","image_url":"luigi.jpg"},
            {"character_name":"ネス","image_url":"ness.jpg"},
            {"character_name":"CF","image_url":"captain_falcon.jpg"},
            {"character_name":"プリン","image_url":"purin.jpg"},
            {"character_name":"ピーチ","image_url":"peach.jpg"},
            {"character_name":"デイジー","image_url":"daisy.jpg"},
            {"character_name":"クッパ","image_url":"koopa.jpg"},
            {"character_name":"アイスクライマー","image_url":"ice_climber.jpg"},
            {"character_name":"シーク","image_url":"sheik.jpg"},
            {"character_name":"ゼルダ","image_url":"zelda.jpg"},
            {"character_name":"ドクターマリオ","image_url":"drmario.jpg"},
            {"character_name":"ピチュー","image_url":"pichu.jpg"},
            {"character_name":"ファルコ","image_url":"falco.jpg"},
            {"character_name":"マルス","image_url":"marth.jpg"},
            {"character_name":"ルキナ","image_url":"lucina.jpg"},
            {"character_name":"こどもリンク","image_url":"young_link.jpg"},
            {"character_name":"ガノンドロフ","image_url":"ganondorf.jpg"},
            {"character_name":"ミューツー","image_url":"mewtwo.jpg"},
            {"character_name":"ロイ","image_url":"roy.jpg"},
            {"character_name":"クロム","image_url":"chrom.jpg"},
            {"character_name":"ゲーム＆ウォッチ","image_url":"game_and_watch.jpg"},
            {"character_name":"メタナイト","image_url":"meta_knight.jpg"},
            {"character_name":"ピット","image_url":"pit.jpg"},
            {"character_name":"ブラックピット","image_url":"black_pit.jpg"},
            {"character_name":"ゼロスーツサムス","image_url":"zero_suit_samus.jpg"},
            {"character_name":"ワリオ","image_url":"wario.jpg"},
            {"character_name":"スネーク","image_url":"snake.jpg"},
            {"character_name":"アイク","image_url":"ike.jpg"},
            {"character_name":"ポケトレ","image_url":"Pokemon_trainer.jpg"},
            {"character_name":"ディディコング","image_url":"dd.jpg"},
            {"character_name":"ルカ","image_url":"lucas.jpg"},
            {"character_name":"ソニック","image_url":"sonic.jpg"},
            {"character_name":"デデデ","image_url":"ddd.jpg"},
            {"character_name":"ピクオリ","image_url":"pikumin_and_orimar.jpg"},
            {"character_name":"ルカリオ","image_url":"lucario.jpg"},
            {"character_name":"ロボット","image_url":"robot.jpg"},
            {"character_name":"トゥーンリンク","image_url":"toon_link.jpg"},
            {"character_name":"ウルフ","image_url":"wolf.jpg"},
            {"character_name":"村人","image_url":"murabito.jpg"},
            {"character_name":"ロックマン","image_url":"rockman.jpg"},
            {"character_name":"フィットレ","image_url":"fit_trainer.jpg"},
            {"character_name":"ロゼチコ","image_url":"rose_chiko.jpg"},
            {"character_name":"リトルマック","image_url":"little_mac.jpg"},
            {"character_name":"ゲッコウガ","image_url":"gekkouga.jpg"},
            {"character_name":"パルテナ","image_url":"palutena.jpg"},
            {"character_name":"パックマン","image_url":"pac_man.jpg"},
            {"character_name":"ルフレ","image_url":"reflet.jpg"},
            {"character_name":"シュルク","image_url":"shulk.jpg"},
            {"character_name":"クッパジュニア","image_url":"koopa_jr.jpg"},
            {"character_name":"ダックハント","image_url":"duck_hunt.jpg"},
            {"character_name":"リュウ","image_url":"ryu.jpg"},
            {"character_name":"ケン","image_url":"ken.jpg"},
            {"character_name":"クラウド","image_url":"cloud.jpg"},
            {"character_name":"カムイ","image_url":"kamui.jpg"},
            {"character_name":"ベヨネッタ","image_url":"bayonetta.jpg"},
            {"character_name":"インクリング","image_url":"inkling.jpg"},
            {"character_name":"リドリー","image_url":"ridley.jpg"},
            {"character_name":"シモン","image_url":"simon.jpg"},
            {"character_name":"リヒター","image_url":"richter.jpg"},
            {"character_name":"キングクルール","image_url":"king_k_rool.jpg"},
            {"character_name":"しずえ","image_url":"shizue.jpg"},
            {"character_name":"ガオガエン","image_url":"gaogaen.jpg"},
            {"character_name":"パックンフラワー","image_url":"packun_flower.jpg"},
            {"character_name":"ジョーカー","image_url":"joker.jpg"},
            {"character_name":"勇者","image_url":"hero.jpg"},
            {"character_name":"バンカズ","image_url":"bankazu.jpg"},
            {"character_name":"テリー","image_url":"terry.jpg"},
            {"character_name":"ベレス","image_url":"byleth.jpg"},
            {"character_name":"メンメン","image_url":"minmin.jpg"},
            {"character_name":"スティーブ","image_url":"steve.jpg"},
            {"character_name":"セフィロス","image_url":"sephiroth.jpg"},
            {"character_name":"ホムヒカ","image_url":"homuhika.jpg"},
            {"character_name":"カズヤ","image_url":"kazuya.jpg"},
            {"character_name":"ソラ","image_url":"sora.jpg"},
            {"character_name":"格闘mii","image_url":"mii_brawler.jpg"},
            {"character_name":"剣術mii","image_url":"mii_sword.jpg"},
            {"character_name":"射撃mii","image_url":"mii_gunner.jpg"},
        ]

        for data in characters:
            character = Character(**data)
            character.save()

        self.stdout.write(self.style.SUCCESS('this command Success'))