# Generated by Django 4.1.7 on 2023-10-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smash_note', '0003_favoritecharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='player_character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_character', to='smash_note.character'),
        ),
    ]
