# Generated by Django 4.1.7 on 2025-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_note', '0006_alter_character_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
